name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip zip unzip openjdk-17-jdk wget git

      - name: Install Buildozer
        run: |
          pip install --break-system-packages --upgrade git+https://github.com/kivy/buildozer.git@master

      - name: Setup Android SDK
        run: |
          ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          mkdir -p latest
          mv cmdline-tools/* latest/
          # Create symlink in the old path Buildozer expects
          mkdir -p $ANDROID_HOME/tools
          ln -s $ANDROID_HOME/cmdline-tools/latest $ANDROID_HOME/tools/cmdline-tools
          # Accept licenses and install build-tools
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.1.0" "platforms;android-34"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
