name: Build Kivy App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
            .buildozer_global
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      # ✅ Fork che non usa chown e funziona perfettamente su GitHub Actions
      - name: Build with Buildozer (fixed)
        uses: GabrielBB/buildozer-action@main
        with:
          command: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
